name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to GITHUB_TOKEN

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training and generate model
      run: |
        python train.py

    - name: Generate gameplay GIF
      run: |
        python play.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push model and GIF if changed
      run: |
        git add tetris_model.pth tetris.gif
        git diff --staged --quiet || git commit -m "CI: Update trained Tetris model and gameplay GIF"
        git push